# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bec83402398c97705ff85bc7be67a7f0b3d3c85d5f9a8797d015330c9adf787c7e7e052c303ce2e0a19f87ac553e938aaa6049932d0b0bc705aa2e69f7692d37

test:
  secret_key_base: 5965177fa99057bb58590317729ea8c3fb3c11cc4f2c30ffeb58d3be0ed47d88c4f96df2458fc2839b223780bc18eddb183a452f6fd19906c966182958f881c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
